version: '3'
services:
  api:
    build: .
    ports:
      - "8888:8888"
      - "8080:8080"
    command: opt/eval-cso/eval-ex
    depends_on:
      - migration
      - postgres

  migration:
     build: .
     command: opt/eval-cso/eval-migrate
     depends_on:
       - postgres

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: $APP_DB_NAME
      POSTGRES_USER: $APP_DB_USER
      POSTGRES_PASSWORD: $APP_DB_PASSWORD
