resolver: lts-13.19

packages:
  - eval-cso

extra-deps:
  - base-noprelude-4.12.0.0
  - aeson-options-0.1.0
  - esqueleto-2.7.0
  - random-strings-0.1.1.0@sha256:935a7a23dab45411960df77636a29b44ce42b89eeb15f2b1e809d771491fa677

ghc-options:
  "$locals": -fhide-source-paths
