<<: !include "../hpack/module.yaml"

name: eval
library:
  <<: *lib-common
  dependencies:
    - aeson
    - aeson-options
    - bytestring
    - cryptonite
    - esqueleto
    - ekg
    - http-types
    - http-api-data
    - microlens-platform
    - monad-logger
    - monad-time
    - persistent
    - persistent-postgresql
    - persistent-template
    - resource-pool
    - random-strings
    - servant-errors
    - servant-server
    - servant-auth
    - servant-auth-server
    - text
    - time
    - unliftio-core
    - yaml
    - warp
    - wai
    - wai-cors
    - wai-extra

executables:
  eval-ex :
    <<: *exec-common
    source-dirs: app
    dependencies:
      - eval
  eval-migrate :
    <<: *exec-common
    source-dirs: migration
    dependencies:
      - eval
