<<: !include "../hpack/module.yaml"

name: eval-cso

library:
  <<: *lib-common
  dependencies:
    - aeson
    - aeson-options
    - bytestring
    - co-log
    - cryptonite
    - microlens-platform
    - monad-logger
    - monad-time
    - persistent
    - persistent-postgresql
    - persistent-template
    - servant-server
    - servant-auth
    - servant-auth-server
    - text
    - time
    - unliftio-core
    - warp
    - wai
    - wai-extra

executables:
  eval-cso :
    <<: *exec-common
    source-dirs: app
    dependencies:
      - eval-cso
      - persistent-postgresql
      - servant-server
      - unliftio-core
      - wai
      - warp
